Powerfront.BackendTest/Controllers/OperatorController.cs
using Newtonsoft.Json;
using Powerfront.BackendTest.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Web.Mvc;

namespace Powerfront.BackendTest.Controllers
{
    public class OperatorController : Controller
    {
        private IEnumerable<OperatorReportItem> LoadReport(ProductivityReportCriteria filter)
        {
            var result = new List<OperatorReportItem>();

            var cs = ConfigurationManager.ConnectionStrings["chat"].ConnectionString;

            using (var conn = new SqlConnection(cs))
            using (var sqlcomm = conn.CreateCommand())
            {
                sqlcomm.CommandText = "dbo.OperatorProductivityRef";
                sqlcomm.CommandType = CommandType.StoredProcedure;

                if (filter != null)
                {
                    if (!string.IsNullOrWhiteSpace(filter.Device))
                    {
                        sqlcomm.Parameters
                            .AddWithValue("@Device", filter.Device)
                            .SqlDbType = SqlDbType.VarChar;
                    }

                    if (filter.EndDate.HasValue)
                    {
                        sqlcomm.Parameters
                            .AddWithValue("@EndDate", filter.EndDate.Value)
                            .SqlDbType = SqlDbType.DateTime2;
                    }

                    if (filter.StartDate.HasValue)
                    {
                        sqlcomm.Parameters
                            .AddWithValue("@StartDate", filter.StartDate)
                            .SqlDbType = SqlDbType.DateTime2;
                    }

                    if (!string.IsNullOrWhiteSpace(filter.Website))
                    {
                        sqlcomm.Parameters
                            .AddWithValue("@Website", filter.Website)
                            .SqlDbType = SqlDbType.VarChar;
                    }
                }

                conn.Open();

                var dr = sqlcomm.ExecuteReader();

                if (dr != null && dr.HasRows)
                {
                    while (dr.Read())
                    {
                        var reportItem = new OperatorReportItem();
                        reportItem.ID = dr.GetInt32(0);
                        reportItem.Name = dr.GetString(1);
                        reportItem.ProactiveSent = dr.IsDBNull(2) ? 0 : (int)dr[2];
                        reportItem.ProactiveAnswered = dr.IsDBNull(3) ? 0 : dr.GetInt32(3);
                        reportItem.ReactiveReceived = dr.IsDBNull(4) ? 0 : dr.GetInt32(4);
                        reportItem.ReactiveAnswered = dr.IsDBNull(5) ? 0 : dr.GetInt32(5);
                        reportItem.TotalChatLengthSeconds = dr.IsDBNull(6) ? 0 : dr.GetInt32(6);
                        reportItem.AverageChatLengthSeconds = dr.IsDBNull(7) ? 0 : dr.GetInt32(7);

                        if (reportItem.ProactiveSent != 0)
                        {
                            reportItem.ProactiveResponseRate = Convert
                                .ToInt32((double)reportItem.ProactiveAnswered / reportItem.ProactiveSent * 100);
                        }

                        if (reportItem.ReactiveReceived != 0)
                        {
                            reportItem.ReactiveResponseRate = Convert
                                .ToInt32((double)reportItem.ReactiveAnswered / reportItem.ReactiveReceived * 100);
                        }

                        result.Add(reportItem);
                    }
                }
            }

            return result;
        }

        [HttpGet]
        public ActionResult ProductivityReport()
        {
            var model = new OperatorReportViewModelRef();

            ViewBag.Message = "Operator Productivity Report";

            return View(model);
        }

        public ActionResult ProductivityReportTable(ProductivityReportCriteria filter)
        {
            ActionResult result = null;

            try
            {
                var model = LoadReport(filter);
                result = PartialView(model);
            }
            catch (SqlException se)
            {
                Trace.WriteLine($"Failed to open the data store, due to exception:{Environment.NewLine}{se}");
                result = new HttpStatusCodeResult(400, se.Message);
            }
            catch (Exception ex)
            {
                Trace.WriteLine($"Failed to load the report, due to exception:{Environment.NewLine}{ex}");
                result = new HttpStatusCodeResult(500, "The report cannot be generated. Try again later.");
            }

            return result;
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult ProductivityReportCsv(string filterDump)
        {
            var filter = JsonConvert.DeserializeObject<ProductivityReportCriteria>(filterDump);

            ActionResult result = null;
            IEnumerable<OperatorReportItem> data = null;

            try
            {
                data = LoadReport(filter);
            }
            catch (SqlException se)
            {
                Trace.WriteLine($"Failed to open the data store, due to exception:{Environment.NewLine}{se}");
                result = new HttpStatusCodeResult(400, se.Message);
            }
            catch (Exception ex)
            {
                Trace.WriteLine($"Failed to load the report, due to exception:{Environment.NewLine}{ex}");
                result = new HttpStatusCodeResult(500, "The report cannot be generated. Try again later.");
            }

            if (data != null)
            {
                var sb = new StringBuilder();


                var lines = $"Operator ID,Name,Proactive Sent,Proactive Answered,Proactive Response Rate [%],Reactive Received,Reactive Answered,Reactive Response Rate [%],Total Chat Length [sec],Average Chat Length[sec]{Environment.NewLine}";

                lines += data.Aggregate(string.Empty, 
                    (c, n) => c += $"{n.ID},{n.Name},{n.ProactiveSent},{n.ProactiveAnswered},{n.ProactiveResponseRate},{n.ReactiveReceived},{n.ReactiveAnswered},{n.ReactiveResponseRate},{n.TotalChatLengthSeconds},{n.AverageChatLengthSeconds}{Environment.NewLine}");

                result = File(Encoding.UTF8.GetBytes(lines), "text/csv", "ProductivityReport.csv");
            }

            return result;
        }
    }
}

Powerfront.BackendTest/Views/Operator/ProductivityReport.cshtml
@using Powerfront.BackendTest.Models

@model OperatorReportViewModelRef

@{
    ViewBag.Title = "Operator Report";

    var deviceListItems = new List<SelectListItem>
{
new SelectListItem { Text = "[ Any ]", Value = "Any", Selected = true }
};

    deviceListItems.AddRange(Model.DeviceList.Select(d => new SelectListItem { Text = d, Value = d }));

    var websiteListItems = new List<SelectListItem>
{
new SelectListItem { Text = "[ Any ]", Value = "Any", Selected = true }
};

    websiteListItems.AddRange(Model.WebsiteList.Select(w => new SelectListItem { Text = w, Value = w }));

    var predefinedPeriodListItems = new List<SelectListItem>
{
new SelectListItem { Text = "[ None ]", Value = "None", Disabled = true }
};

    predefinedPeriodListItems.AddRange(Model.PredefinedDateFilter.Select(kvp => new SelectListItem { Text = kvp.Key, Value = kvp.Value }));
}

<link href="~/Content/bootstrap-datepicker3.css" rel="stylesheet" />

<h2>Operator Report</h2>

<div class="row">
    <div class="col-2">
        <div id="predefinedPeriodFilterRadio" class="radio">
            <label>
                @Html.RadioButton("PeriodFilterType", "pre-defined", true)
                Pre-defined
            </label>
        </div>

        <div id="customPeriodFilterRadio" class="radio">
            <label>
                @Html.RadioButton("PeriodFilterType", "custom")
                Custom
            </label>
        </div>
    </div>

    <div class="col-3">
        <div id="predefinedPeriodHandles">
            @Html.DropDownListFor(m => m.PredefinedDateFilter, predefinedPeriodListItems, new { id = "periodMaskDropDown", @class = "form-control" })
        </div>

        <div id="customPeriodHandles" class="d-none">
            <div class="row">
                <div class="col-8">
                    @Html.TextBoxFor(m => m.StartDate, new { id = "startDateInput", @class = "form-control", placeholder = "Start Date" })
                    <br />
                    @Html.TextBoxFor(m => m.EndDate, new { id = "endDateInput", @class = "form-control", placeholder = "End Date" })
                </div>
                <div class="col-4">
                    <button id="applyPeriodButton" type="button" class="btn btn-secondary">Apply</button>
                </div>
            </div>
        </div>
    </div>

    <div class="col-2 text-right">
        <label class="col-form-label">
            Device
        </label>

        <br />
        <br />
        <label class="col-form-label">
            Website
        </label>
    </div>

    <div class="col-3">
        @Html.DropDownListFor(m => m.DeviceList, deviceListItems, new { id = "deviceDropDown", @class = "form-control" })
        <br />
        @Html.DropDownListFor(m => m.WebsiteList, websiteListItems, new { id = "websiteDropDown", @class = "form-control" })
    </div>
</div>

<br />

<span class="text-info">HINT: The sample data is found in March, 2017</span>
<div id="reportArea">
    @if (Model.Rows != null && Model.Rows.Count() > 0)
    {
        Html.Partial("_ProductivityReportTable", Model.Rows);
    }
</div>
<br />

@using (Html.BeginForm("ProductivityReportCsv", "Operator", FormMethod.Post, new { id = "exportForm" }))
{
    @Html.AntiForgeryToken()
    <input type="hidden" name="filterDump" />
    <input type="submit" class="btn btn-secondary" value="CSV Export" />
}

<span id="exportFeedback" class="invisible"></span>

@section Scripts {
    <script src="~/Scripts/bootstrap-datepicker.min.js"></script>

    <script>
        $(document).ready(Document_Ready);

        function ApplyFilter() {
            var payload = PrepareFilter();

            debugger;

            if (IsValidFilter(payload)) {
                var settings = {
                    type: "POST",
                    contentType: "application/json",
                    url: "/Operator/ProductivityReportTable",
                    data: JSON.stringify(payload)
                };

                settings.success = function (response) {
                    $(reportArea).html(response);
                };

                settings.error = function (response) {
                    $(reportArea).html("<span class='text-danger'>Error occured!</span>");
                };

                settings.complete = function (response) {
                    $("body").css("cursor", "default");
                }

                $("body").css("cursor", "wait");
                $.ajax(settings);
            }
        }

        function CsvExport() {
            $(exportFeedback).addClass("invisible");

            var filter = PrepareFilter();

            if (IsValidFilter(filter)) {
                $(exportForm).children("input[name=filterDump]").val(JSON.stringify(filter));
            }
        }

        function Document_Ready(e) {
            var calendarDefaults = {
                autoclose: true,
                todayHighlight: true,
                todayBtn: "linked",
                endDate: new Date(2018, 4, 13)
            };

            $(startDateInput).datepicker(calendarDefaults);
            $(endDateInput).datepicker(calendarDefaults);

            $(periodMaskDropDown)
                .children()
                .filter(function () { return $(this).html() == "Last Month"; })
                .prop("selected", true)
            ;

            ApplyFilter();

            $(".radio").on("click", PeriodMaskRadio_Click);

            $(deviceDropDown).on("change", ApplyFilter);
            $(periodMaskDropDown).on("change", ApplyFilter);
            $(websiteDropDown).on("change", ApplyFilter);
            $(applyPeriodButton).on("click", ApplyFilter);
            $(exportForm).submit(CsvExport);
        }

        function PeriodMaskRadio_Click(e) {
            var sender = $(e.target).closest("div");

            if (sender.is(predefinedPeriodFilterRadio)) {
                $(customPeriodHandles).addClass("d-none");
                $(predefinedPeriodHandles).removeClass("d-none");
            }
            else if (sender.is(customPeriodFilterRadio)) {
                $(predefinedPeriodHandles).addClass("d-none");
                $(customPeriodHandles).removeClass("d-none");
            }
        }

        function PrepareFilter() {
            var result = {
                Device: $(deviceDropDown).val() == "Any" ? null : $(deviceDropDown).val(),
                EndDate: $(endDateInput).val().trim() == "" ? null : $(endDateInput).datepicker("getDate"),
                StartDate: $(startDateInput).val().trim() == "" ? null : $(startDateInput).datepicker("getDate"),
                Website: $(websiteDropDown).val() == "Any" ? null : $(websiteDropDown).val()
            };

            if ($("input[name=PeriodFilterType]:checked").val() === "pre-defined") {
                var ma = $(periodMaskDropDown).val().split("/");

                ma.length > 0 && (result.StartDate = new Date(parseInt(ma[0])));
                ma.length > 1 && (result.EndDate = new Date(parseInt(ma[1])));
            }

            return result;
        }

        function IsValidFilter(filter) {
            var result = filter.EndDate == null || (filter.EndDate > filter.StartDate);

            if (filter.EndDate && (filter.EndDate < filter.StartDate)) {
                alert("Invalid period. End Date must be greater than Start Date.");
            }

            return result;
        }
    </script>
}

Powerfront.BackendTest/Views/Operator/ProductivityReportTable.cshtml
@model IEnumerable<Powerfront.BackendTest.OperatorReportItem>

@{ 
    Func<int, string> formatDuration = seconds =>
    {
        var result = "0s";

        var ts = TimeSpan.FromSeconds(seconds);

        var units = new Dictionary<char, int>(4)
        {
            { 'd', ts.Days },
            { 'h', ts.Hours },
            { 'm', ts.Minutes},
            { 's', ts.Seconds }
        };

        var calculated = units
            .SkipWhile(u => u.Value == 0)
            .Aggregate(string.Empty, (c, n) => c += $"{n.Value}{n.Key} ");

        if (!string.IsNullOrEmpty(calculated))
        {
            result = calculated.TrimEnd();
        }

        return result;
    };
}
<style>
    table {
    }

        table th {
            text-align: center;
            vertical-align: middle;
        }

        table td {
            text-align: right;
        }

            table td:nth-child(2) {
                text-align: left
            }
</style>

<table class="table table-bordered">
    <thead>
        <tr>
            <th rowspan="2">S.No.</th>
            <th rowspan="2">Operator Name</th>
            <th colspan="3">Proactive</th>
            <th colspan="3">Reactive</th>
            <th colspan="2">Chat duration</th>
        </tr>

        <tr>
            <th>Sent</th>
            <th>Answered</th>
            <th>Rate [%]</th>
            <th>Received</th>
            <th>Answered</th>
            <th>Rate [%]</th>
            <th>Total</th>
            <th>Average</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.ID</td>
                <td>@item.Name</td>
                <td>@item.ProactiveSent</td>
                <td>@item.ProactiveAnswered</td>
                <td>@item.ProactiveResponseRate</td>
                <td>@item.ReactiveReceived</td>
                <td>@item.ReactiveAnswered</td>
                <td>@item.ReactiveResponseRate</td>
                <td>@formatDuration(item.TotalChatLengthSeconds)</td>
                <td>@formatDuration(item.AverageChatLengthSeconds)</td>
            </tr>
        }
    </tbody>
</table>